ipc: addd qb_ipcc_auth_get() API call
ClusterLabs/libqb pull request #418
Opened 2020-09-24 08:34 UTC by chrissie-c

We can't use SO_PEERCRED on the client fd when using socket IPC
becayse it's a DGRAM socket (pacemaker tries this). So provide
an API to get the server credentials that libqb has already
squirreled away for its own purposes.

Also, fix some unused-variable compiler warnings in unix.c
when building on systems withpout posix_fallocate().

2020-09-24 17:23 UTC, kgaillot requested changes
Nice, I think any IPC users will eventually find this handy :)

covscan is complaining but that's probably because Fabio upgraded the covscan version rather than related issues. I can't wait to see what it finds in Pacemaker ;)

2020-09-24 17:23 UTC, kgaillot commented on lib/ipc_int.h
> +	uid_t euid;
I'd add this to the end of the struct so you don't have to bump the shared library version. Uglier, but library bumps are a hassle

2020-09-24 17:23 UTC, kgaillot commented on lib/ipcc.c
> +	*gid = c->egid;
For flexibility, I wouldn't require these to be non-NULL but wrap the assignments in if != NULL. That way callers can get just one or two values if that's all they need.

2020-09-25 09:44 UTC, chrissie-c commented
Update commit in the CI now. It's still failing covscan but those are stupid errors in the test suite so I'm happy to ignore them (they'll go in the  ignore list for next time once it commited).

I have the pacemaker patch to use this APi largely ready to go too.

2020-09-25 20:57 UTC, kgaillot commented
looks good to me

2020-09-25 20:57 UTC, kgaillot approved these changes

2020-09-28 08:53 UTC, merged

2020-09-28 08:53 UTC, chrissie-c commented
Thanks for the review!